// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	// 订单列表, 分页, 按 ID 倒排
	ListSimpleOrder(ctx context.Context, in *ListSimpleOrderRequest, opts ...grpc.CallOption) (*ListSimpleOrderResponse, error)
	// 通过订单ID获取列表详情
	GetOrderDetailById(ctx context.Context, in *GetOrderDetailByIdRequest, opts ...grpc.CallOption) (*GetOrderDetailByIdResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) ListSimpleOrder(ctx context.Context, in *ListSimpleOrderRequest, opts ...grpc.CallOption) (*ListSimpleOrderResponse, error) {
	out := new(ListSimpleOrderResponse)
	err := c.cc.Invoke(ctx, "/order.order.OrderService/ListSimpleOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderDetailById(ctx context.Context, in *GetOrderDetailByIdRequest, opts ...grpc.CallOption) (*GetOrderDetailByIdResponse, error) {
	out := new(GetOrderDetailByIdResponse)
	err := c.cc.Invoke(ctx, "/order.order.OrderService/GetOrderDetailById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations should embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	// 订单列表, 分页, 按 ID 倒排
	ListSimpleOrder(context.Context, *ListSimpleOrderRequest) (*ListSimpleOrderResponse, error)
	// 通过订单ID获取列表详情
	GetOrderDetailById(context.Context, *GetOrderDetailByIdRequest) (*GetOrderDetailByIdResponse, error)
}

// UnimplementedOrderServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) ListSimpleOrder(context.Context, *ListSimpleOrderRequest) (*ListSimpleOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSimpleOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderDetailById(context.Context, *GetOrderDetailByIdRequest) (*GetOrderDetailByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderDetailById not implemented")
}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_ListSimpleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSimpleOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListSimpleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.order.OrderService/ListSimpleOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListSimpleOrder(ctx, req.(*ListSimpleOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderDetailById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderDetailByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderDetailById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.order.OrderService/GetOrderDetailById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderDetailById(ctx, req.(*GetOrderDetailByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSimpleOrder",
			Handler:    _OrderService_ListSimpleOrder_Handler,
		},
		{
			MethodName: "GetOrderDetailById",
			Handler:    _OrderService_GetOrderDetailById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
